OPTS <- list(
    cores=4,
    sample=c(1,2),
    target="oncoseq1500-v4",
    target.fn=system.file("extdata/onco1500-v4-targets-hg38-ucsc.bed.gz", package="cnvex"),
    gene.fn=system.file("extdata/gene/motr.v2-prot.gff3", package="cnvex"),
    segment="joint",
    caller="vardict",
    chr.names="ucsc",
    skip.chr="chrM",
    min.gap=50000,
    shoulder=300,
    tilewidth=NA_integer_,
    tileflank=NA_integer_,
    min.seg=2,
    max.K=30,
    sd.penalty=1,
    local.sd=FALSE,
    grid.n=64,
    p.lo=0.05,
    p.hi=0.95,
    D.lo=1,
    D.hi=6,
    max.C=9,
    max.sC=20,
    max.len.per.probe=1e6,
    res=0.1,
    gc.adjust.trend=FALSE,
    gc.adjust.offset=FALSE,
    gc.adjust.span.on=0.35,
    gc.adjust.span.off=0.35,
    gc.adjust.on=c(0.3, 0.7),
    gc.adjust.off=c(0.0, 1.0),
    lr.smooth="outlier",
    lr.smooth.window=7
)
